[package]
name = "{{ package }}"
version = "0.1.0"
edition = "2024"

[dependencies]
dynamic-rust = { git = "{{ lock.libraries["dynamic-rust"].repository }}", rev = "{{ lock.libraries["dynamic-rust"].revision }}", features = ["axum"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
